#pragma once
#include "./pch.h"
#include "./core/container/types.h"

namespace Raydiance
{
	namespace Graphics
	{
		enum class RHI_ResourceFormat : uint8
		{
			RHI_RESOURCE_FORMAT_INVALID					= 0x00,
			RHI_RESOURCE_FORMAT_R8_UINT					= 0x01,
			RHI_RESOURCE_FORMAT_R8_SINT					= 0x02,
			RHI_RESOURCE_FORMAT_R8_UNORM				= 0x03,
			RHI_RESOURCE_FORMAT_R8_SNORM				= 0x04,
			RHI_RESOURCE_FORMAT_R8G8_UINT				= 0x05,
			RHI_RESOURCE_FORMAT_R8G8_SINT				= 0x06,
			RHI_RESOURCE_FORMAT_R8G8_UNORM				= 0x07,
			RHI_RESOURCE_FORMAT_R8G8_SNORM				= 0x08,
			RHI_RESOURCE_FORMAT_R8G8B8A8_UINT			= 0x09,
			RHI_RESOURCE_FORMAT_R8G8B8A8_SINT			= 0x0A,
			RHI_RESOURCE_FORMAT_R8G8B8A8_UNORM			= 0x0B,
			RHI_RESOURCE_FORMAT_R8G8B8A8_SNORM			= 0x0C,
			RHI_RESOURCE_FORMAT_R8G8B8A8_UNORM_SRGB		= 0x0D,
			RHI_RESOURCE_FORMAT_B8G8R8A8_UNORM			= 0X0E,
			RHI_RESOURCE_FORMAT_B8G8R8A8_UNORM_SRGB		= 0x0F,
			RHI_RESOURCE_FORMAT_R16_UINT				= 0x10,
			RHI_RESOURCE_FORMAT_R16_SINT				= 0x11,
			RHI_RESOURCE_FORMAT_R16_UNORM				= 0x12,
			RHI_RESOURCE_FORMAT_R16_SNORM				= 0x13,
			RHI_RESOURCE_FORMAT_R16_FLOAT				= 0x14,
			RHI_RESOURCE_FORMAT_R16G16_UINT				= 0x15,
			RHI_RESOURCE_FORMAT_R16G16_SINT				= 0x16,
			RHI_RESOURCE_FORMAT_R16G16_UNORM			= 0x17,
			RHI_RESOURCE_FORMAT_R16G16_SNORM			= 0x18,
			RHI_RESOURCE_FORMAT_R16G16_FLOAT			= 0x19,
			RHI_RESOURCE_FORMAT_R16G16B16A16_UINT		= 0x1A,
			RHI_RESOURCE_FORMAT_R16G16B16A16_SINT		= 0x1B,
			RHI_RESOURCE_FORMAT_R16G16B16A16_UNORM		= 0x1C,
			RHI_RESOURCE_FORMAT_R16G16B16A16_SNORM		= 0x1D,
			RHI_RESOURCE_FORMAT_R16G16B16A16_FLOAT		= 0x1E,
			RHI_RESOURCE_FORMAT_R32_UINT				= 0x1F,
			RHI_RESOURCE_FORMAT_R32_SINT				= 0x20,
			RHI_RESOURCE_FORMAT_R32_FLOAT				= 0x21,
			RHI_RESOURCE_FORMAT_R32G32_UINT				= 0x22,
			RHI_RESOURCE_FORMAT_R32G32_SINT				= 0x23,
			RHI_RESOURCE_FORMAT_R32G32_FLOAT			= 0x24,
			RHI_RESOURCE_FORMAT_R32G32B32_UINT			= 0x25,
			RHI_RESOURCE_FORMAT_R32G32B32_SINT			= 0x26,
			RHI_RESOURCE_FORMAT_R32G32B32_FLOAT			= 0x27,
			RHI_RESOURCE_FORMAT_R32G32B32A32_UINT		= 0x28,
			RHI_RESOURCE_FORMAT_R32G32B32A32_SINT		= 0x29,
			RHI_RESOURCE_FORMAT_R32G32B32A32_FLOAT		= 0x2A,
			RHI_RESOURCE_FORMAT_D16_UNORM				= 0x2B,
			RHI_RESOURCE_FORMAT_D24_UNORM_S8_UINT		= 0x2C,
			RHI_RESOURCE_FORMAT_D32_FLOAT				= 0x2D,
			RHI_RESOURCE_FORMAT_D32_FLOAT_S8_UINT		= 0x2E,
			RHI_RESOURCE_FORMAT_B4G4R4A4_UNORM			= 0x2F,
			RHI_RESOURCE_FORMAT_BC1_UNORM				= 0x30,
			RHI_RESOURCE_FORMAT_BC1_UNORM_SRGB			= 0x31,
			RHI_RESOURCE_FORMAT_BC2_UNORM				= 0x32,
			RHI_RESOURCE_FORMAT_BC2_UNORM_SRGB			= 0x33,
			RHI_RESOURCE_FORMAT_BC3_UNORM				= 0x34,
			RHI_RESOURCE_FORMAT_BC3_UNORM_SRGB			= 0x35,
			RHI_RESOURCE_FORMAT_BC4_UNORM				= 0x36,
			RHI_RESOURCE_FORMAT_BC4_SNORM				= 0x37,
			RHI_RESOURCE_FORMAT_BC5_UNORM				= 0x38,
			RHI_RESOURCE_FORMAT_BC5_SNORM				= 0x39,
			RHI_RESOURCE_FORMAT_BC6H_UFLOAT				= 0x3A,
			RHI_RESOURCE_FORMAT_BC6H_SFLOAT				= 0x3B,
			RHI_RESOURCE_FORMAT_BC7_UNORM				= 0x3C,
			RHI_RESOURCE_FORMAT_BC7_UNORM_SRGB			= 0x3D,
			RHI_RESOURCE_FORMAT_B5G6R5_UNORM			= 0x3E,
			RHI_RESOURCE_FORMAT_B5G5R5A1_UNORM			= 0x3F,
		};

		inline std::string RHI_ResourceFormat_ToString(RHI_ResourceFormat _format)
		{
			switch (_format)
			{
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_INVALID:               
				return "RHI_RESOURCE_FORMAT_INVALID";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8_UINT:              
				return "RHI_RESOURCE_FORMAT_R8_UINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8_SINT:              
				return "RHI_RESOURCE_FORMAT_R8_SINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8_UNORM:             
				return "RHI_RESOURCE_FORMAT_R8_UNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8_SNORM:             
				return "RHI_RESOURCE_FORMAT_R8_SNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8_UINT:            
				return "RHI_RESOURCE_FORMAT_R8G8_UINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8_SINT:            
				return "RHI_RESOURCE_FORMAT_R8G8_SINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8_UNORM:           
				return "RHI_RESOURCE_FORMAT_R8G8_UNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8_SNORM:           
				return "RHI_RESOURCE_FORMAT_R8G8_SNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8B8A8_UINT:        
				return "RHI_RESOURCE_FORMAT_R8G8B8A8_UINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8B8A8_SINT:        
				return "RHI_RESOURCE_FORMAT_R8G8B8A8_SINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8B8A8_UNORM:       
				return "RHI_RESOURCE_FORMAT_R8G8B8A8_UNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8B8A8_SNORM:       
				return "RHI_RESOURCE_FORMAT_R8G8B8A8_SNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8B8A8_UNORM_SRGB:  
				return "RHI_RESOURCE_FORMAT_R8G8B8A8_UNORM_SRGB";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_B8G8R8A8_UNORM:       
				return "RHI_RESOURCE_FORMAT_B8G8R8A8_UNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_B8G8R8A8_UNORM_SRGB:  
				return "RHI_RESOURCE_FORMAT_B8G8R8A8_UNORM_SRGB";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16_UINT:             
				return "RHI_RESOURCE_FORMAT_R16_UINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16_SINT:             
				return "RHI_RESOURCE_FORMAT_R16_SINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16_UNORM:            
				return "RHI_RESOURCE_FORMAT_R16_UNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16_SNORM:            
				return "RHI_RESOURCE_FORMAT_R16_SNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16_FLOAT:            
				return "RHI_RESOURCE_FORMAT_R16_FLOAT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16_UINT:          
				return "RHI_RESOURCE_FORMAT_R16G16_UINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16_SINT:          
				return "RHI_RESOURCE_FORMAT_R16G16_SINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16_UNORM:         
				return "RHI_RESOURCE_FORMAT_R16G16_UNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16_SNORM:        
				return "RHI_RESOURCE_FORMAT_R16G16_SNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16_FLOAT:         
				return "RHI_RESOURCE_FORMAT_R16G16_FLOAT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16B16A16_UINT:    
				return "RHI_RESOURCE_FORMAT_R16G16B16A16_UINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16B16A16_SINT:    
				return "RHI_RESOURCE_FORMAT_R16G16B16A16_SINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16B16A16_UNORM:   
				return "RHI_RESOURCE_FORMAT_R16G16B16A16_UNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16B16A16_SNORM:   
				return "RHI_RESOURCE_FORMAT_R16G16B16A16_SNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16B16A16_FLOAT:   
				return "RHI_RESOURCE_FORMAT_R16G16B16A16_FLOAT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32_UINT:             
				return "RHI_RESOURCE_FORMAT_R32_UINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32_SINT:             
				return "RHI_RESOURCE_FORMAT_R32_SINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32_FLOAT:            
				return "RHI_RESOURCE_FORMAT_R32_FLOAT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32_UINT:          
				return "RHI_RESOURCE_FORMAT_R32G32_UINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32_SINT:          
				return "RHI_RESOURCE_FORMAT_R32G32_SINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32_FLOAT:         
				return "RHI_RESOURCE_FORMAT_R32G32_FLOAT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32_UINT:       
				return "RHI_RESOURCE_FORMAT_R32G32B32_UINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32_SINT:       
				return "RHI_RESOURCE_FORMAT_R32G32B32_SINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32_FLOAT:      
				return "RHI_RESOURCE_FORMAT_R32G32B32_FLOAT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32A32_UINT:    
				return "RHI_RESOURCE_FORMAT_R32G32B32A32_UINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32A32_SINT:    
				return "RHI_RESOURCE_FORMAT_R32G32B32A32_SINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32A32_FLOAT:   
				return "RHI_RESOURCE_FORMAT_R32G32B32A32_FLOAT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_D16_UNORM:            
				return "RHI_RESOURCE_FORMAT_D16_UNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_D24_UNORM_S8_UINT:   
				return "RHI_RESOURCE_FORMAT_D24_UNORM_S8_UINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_D32_FLOAT:            
				return "RHI_RESOURCE_FORMAT_D32_FLOAT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_D32_FLOAT_S8_UINT:    
				return "RHI_RESOURCE_FORMAT_D32_FLOAT_S8_UINT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_B4G4R4A4_UNORM:       
				return "RHI_RESOURCE_FORMAT_B4G4R4A4_UNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC1_UNORM:            
				return "RHI_RESOURCE_FORMAT_BC1_UNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC1_UNORM_SRGB:       
				return "RHI_RESOURCE_FORMAT_BC1_UNORM_SRGB";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC2_UNORM:            
				return "RHI_RESOURCE_FORMAT_BC2_UNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC2_UNORM_SRGB:       
				return "RHI_RESOURCE_FORMAT_BC2_UNORM_SRGB";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC3_UNORM:            
				return "RHI_RESOURCE_FORMAT_BC3_UNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC3_UNORM_SRGB:       
				return "RHI_RESOURCE_FORMAT_BC3_UNORM_SRGB";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC4_UNORM:            
				return "RHI_RESOURCE_FORMAT_BC4_UNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC4_SNORM:            
				return "RHI_RESOURCE_FORMAT_BC4_SNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC5_UNORM:            
				return "RHI_RESOURCE_FORMAT_BC5_UNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC5_SNORM:            
				return "RHI_RESOURCE_FORMAT_BC5_SNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC6H_UFLOAT:          
				return "RHI_RESOURCE_FORMAT_BC6H_UFLOAT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC6H_SFLOAT:          
				return "RHI_RESOURCE_FORMAT_BC6H_SFLOAT";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC7_UNORM:            
				return "RHI_RESOURCE_FORMAT_BC7_UNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC7_UNORM_SRGB:       
				return "RHI_RESOURCE_FORMAT_BC7_UNORM_SRGB";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_B5G6R5_UNORM:         
				return "RHI_RESOURCE_FORMAT_B5G6R5_UNORM";
			case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_B5G5R5A1_UNORM:       
				return "RHI_RESOURCE_FORMAT_B5G5R5A1_UNORM";

			default:
				return "RHI_RESOURCE_FORMAT_INVALID: " + std::to_string(static_cast<uint8_t>(_format));
			}
		}


		inline uint32_t GetFormatSize(RHI_ResourceFormat _resourceFormat)
		{
			switch (_resourceFormat)
			{
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_INVALID:
					return 0;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8_SNORM:
					return 1;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8_SNORM:
					return 2;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8B8A8_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8B8A8_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8B8A8_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8B8A8_SNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8B8A8_UNORM_SRGB:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_B8G8R8A8_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_B8G8R8A8_UNORM_SRGB:
					return 4;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16_SNORM:
					return 2;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16_FLOAT:
					return 2;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16_SNORM:
					return 4;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16_FLOAT:
					return 4;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16B16A16_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16B16A16_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16B16A16_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16B16A16_SNORM:
					return 8;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16B16A16_FLOAT:
					return 8;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32_FLOAT:
					return 4;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32_FLOAT:
					return 8;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32_FLOAT:
					return 12;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32A32_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32A32_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32A32_FLOAT:
					return 16;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_D16_UNORM:
					return 2;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_D24_UNORM_S8_UINT:
					return 4;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_D32_FLOAT:
					return 4;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_D32_FLOAT_S8_UINT:
					return 8;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_B4G4R4A4_UNORM:
					return 2;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_B5G6R5_UNORM:
					return 2;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_B5G5R5A1_UNORM:
					return 2;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC1_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC1_UNORM_SRGB:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC4_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC4_SNORM:
					return 8;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC2_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC2_UNORM_SRGB:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC3_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC3_UNORM_SRGB:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC5_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC5_SNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC6H_UFLOAT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC6H_SFLOAT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC7_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC7_UNORM_SRGB:
					return 16;
				
				default:
					return 0;
			}
		}

		inline uint32_t GetElementCount(RHI_ResourceFormat _resourceFormat)
		{
			switch (_resourceFormat)
			{
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8_SNORM:
					return 1;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8_SNORM:
					return 2;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8B8A8_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8B8A8_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8B8A8_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8B8A8_SNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R8G8B8A8_UNORM_SRGB:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_B8G8R8A8_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_B8G8R8A8_UNORM_SRGB:
					return 4;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16_SNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16_FLOAT:
					return 1;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16_SNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16_FLOAT:
					return 2;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16B16A16_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16B16A16_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16B16A16_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16B16A16_SNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R16G16B16A16_FLOAT:
					return 4;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32_FLOAT:
					return 1;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32_FLOAT:
					return 2;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32_FLOAT:
					return 3;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32A32_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32A32_SINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_R32G32B32A32_FLOAT:
					return 4;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_D16_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_D32_FLOAT:
					return 1;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_D24_UNORM_S8_UINT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_D32_FLOAT_S8_UINT:
					return 2;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_B4G4R4A4_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_B5G6R5_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_B5G5R5A1_UNORM:
					return 4;
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC1_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC1_UNORM_SRGB:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC2_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC2_UNORM_SRGB:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC3_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC3_UNORM_SRGB:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC4_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC4_SNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC5_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC5_SNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC6H_UFLOAT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC6H_SFLOAT:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC7_UNORM:
				case RHI_ResourceFormat::RHI_RESOURCE_FORMAT_BC7_UNORM_SRGB:
					return 0;

				default:
					return 0;
			}
		}

	}
}