#pragma once
#include "./core/container/types.h"

namespace Raydiance
{
	namespace Graphics
	{
		enum class RHI_ResourceState : uint8
		{
			RHI_RESOURCE_STATE_INVALID		  = 0x00,
			RHI_RESOURCE_STATE_COMMON		  = 0x01,
			RHI_RESOURCE_STATE_PRESENT		  = 0x02,
			RHI_RESOURCE_STATE_GENERIC_READ   = 0x03,
			RHI_RESOURCE_STATE_GENERIC_WRITE  = 0x04,
			RHI_RESOURCE_STATE_DEPTH_WRITE	  = 0x05,
			RHI_RESOURCE_STATE_RENDER_TEXTURE = 0x06,
			RHI_RESOURCE_STATE_COPY_SRC,
			RHI_RESOURCE_STATE_COPY_DST,
			RHI_RESOURCE_STATE_VERTEX_BUFFER,
			RHI_RESOURCE_STATE_INDEX_BUFFER,
			RHI_RESOURCE_STATE_UNIFORM_BUFFER,
		};
		inline std::string RHI_ResourceState_ToString(RHI_ResourceState _state)
		{
			switch (_state)
			{
			case RHI_ResourceState::RHI_RESOURCE_STATE_INVALID:
				return "RHI_RESOURCE_STATE_INVALID";
			case RHI_ResourceState::RHI_RESOURCE_STATE_COMMON:
				return "RHI_RESOURCE_STATE_COMMON";
			case RHI_ResourceState::RHI_RESOURCE_STATE_PRESENT:
				return "RHI_RESOURCE_STATE_PRESENT";
			case RHI_ResourceState::RHI_RESOURCE_STATE_GENERIC_READ:
				return "RHI_RESOURCE_STATE_GENERIC_READ";
			case RHI_ResourceState::RHI_RESOURCE_STATE_GENERIC_WRITE:
				return "RHI_RESOURCE_STATE_GENERIC_WRITE";
			case RHI_ResourceState::RHI_RESOURCE_STATE_DEPTH_WRITE:
				return "RHI_RESOURCE_STATE_DEPTH_WRITE";
			case RHI_ResourceState::RHI_RESOURCE_STATE_RENDER_TEXTURE:
				return "RHI_RESOURCE_STATE_RENDER_TEXTURE";
			case RHI_ResourceState::RHI_RESOURCE_STATE_COPY_SRC:
				return "RHI_RESOURCE_STATE_COPY_SRC";
			case RHI_ResourceState::RHI_RESOURCE_STATE_COPY_DST:
				return "RHI_RESOURCE_STATE_COPY_DST";
			case RHI_ResourceState::RHI_RESOURCE_STATE_VERTEX_BUFFER:
				return "RHI_RESOURCE_STATE_VERTEX_BUFFER";
			case RHI_ResourceState::RHI_RESOURCE_STATE_INDEX_BUFFER:
				return "RHI_RESOURCE_STATE_INDEX_BUFFER";
			case RHI_ResourceState::RHI_RESOURCE_STATE_UNIFORM_BUFFER:
				return "RHI_RESOURCE_STATE_UNIFORM_BUFFER";
			default:
				return "RHI_RESOURCE_STATE_INVALID: " + std::to_string((uint8)_state);
			}
		}
	}
}